//! Build script — parses clean-room extracted MS-MPEG4 tables from
//! `docs/video/msmpeg4/tables/*.csv` and emits them as compile-time Rust
//! constants. **The Implementer must NOT retype these numbers manually**;
//! they come straight from the CSV produced by the Extractor session
//! from `reference/binaries/wmpcdcs8-2001/mpg4c32.dll` SHA-256
//! `aedb4cf3...b3c099`.
//!
//! The CSV columns per `docs/video/msmpeg4/spec/99-current-understanding.md`
//! §8.1 row for `region_05eac8`:
//!   - Record 0 is the header `(alphabet_size = 128, partition = 64)`.
//!   - Records 1..=128 are `(bit_length, code_value)` u32 pairs for the
//!     v3 joint-MCBPCY canonical-Huffman alphabet.
//!
//! The extractor's CSV column names are historically mis-labelled
//! (`symbol_dec` holds `bit_length`; `bit_length` column holds
//! `code_value`). That's documented in `spec/99` §8.1 as the "suspect
//! in .meta" note — bytes are correct, role labelling is the artefact.
//!
//! Output: `$OUT_DIR/mcbpcy_v3.rs` — an `include!`-able file with:
//!   - `MCBPCY_V3_ALPHABET_SIZE: usize`
//!   - `MCBPCY_V3_PARTITION: usize`
//!   - `MCBPCY_V3_RAW: &[(u32, u32)]` — raw `(bit_length, code_value)`
//!     pairs, one per symbol index 0..127.

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    // Tables are vendored under `tables/` inside the crate for
    // portability. The authoritative source is
    // `docs/video/msmpeg4/tables/` in the workspace; the vendored
    // copies are byte-for-byte identical so `cargo publish` still works.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let tables_dir = manifest_dir.join("tables");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // MCBPCY table — 05eac8.
    let mcbpcy_csv = tables_dir.join("region_05eac8.csv");
    println!("cargo:rerun-if-changed={}", mcbpcy_csv.display());
    emit_mcbpcy_v3(&mcbpcy_csv, &out_dir.join("mcbpcy_v3.rs"));

    // Re-run when the build script itself changes.
    println!("cargo:rerun-if-changed=build.rs");
}

/// Parse `region_05eac8.csv` and emit a Rust file with the raw
/// `(bit_length, code_value)` pairs and the header fields.
fn emit_mcbpcy_v3(csv_path: &Path, out_path: &Path) {
    let text = fs::read_to_string(csv_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", csv_path.display()));

    // Rows: header line + 129 data rows (record 0 is the alphabet header;
    // records 1..=128 are the 128 canonical-Huffman payload entries).
    let mut records: Vec<(u32, u32)> = Vec::with_capacity(129);
    for (line_no, line) in text.lines().enumerate() {
        if line_no == 0 {
            // Skip CSV header.
            continue;
        }
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        // Columns: entry_index, file_offset_hex, symbol_hex, symbol_dec, bit_length
        // Extractor labels: symbol_dec holds bit_length (the first u32),
        // bit_length holds code_value (the second u32). See §8.1.
        let parts: Vec<&str> = line.split(',').collect();
        if parts.len() < 5 {
            panic!("malformed row at line {}: {line}", line_no + 1);
        }
        let bit_length: u32 = parts[3]
            .parse()
            .unwrap_or_else(|_| panic!("bad bit_length at line {}: {}", line_no + 1, parts[3]));
        let code_value: u32 = parts[4]
            .parse()
            .unwrap_or_else(|_| panic!("bad code_value at line {}: {}", line_no + 1, parts[4]));
        records.push((bit_length, code_value));
    }

    if records.len() != 129 {
        panic!(
            "expected 129 records in {} (1 header + 128 payload), got {}",
            csv_path.display(),
            records.len()
        );
    }

    // Record 0 is the header (alphabet_size, partition).
    let (alphabet_size, partition) = records[0];
    if alphabet_size != 128 {
        panic!(
            "unexpected alphabet size {alphabet_size} in {} (expected 128)",
            csv_path.display()
        );
    }
    if partition != 64 {
        panic!(
            "unexpected partition {partition} in {} (expected 64)",
            csv_path.display()
        );
    }

    let mut f = fs::File::create(out_path)
        .unwrap_or_else(|e| panic!("failed to create {}: {e}", out_path.display()));
    writeln!(
        f,
        "// Auto-generated by build.rs from \
         docs/video/msmpeg4/tables/region_05eac8.csv. DO NOT EDIT.\n\
         // Source binary: mpg4c32.dll SHA-256 \
         aedb4cf3d33c8554ab8acf04afe2d936eaa7c49107c5fefe163bca2e94b3c099\n\
         // Role: v3 joint-MCBPCY VLC source (per spec/99 §3.1 / §8.1).\n\
         \n\
         pub const MCBPCY_V3_ALPHABET_SIZE: usize = {};\n\
         pub const MCBPCY_V3_PARTITION: usize = {};\n\
         \n\
         /// 128 × (bit_length, code_value) canonical-Huffman entries for\n\
         /// the v3 joint-MCBPCY VLC. Index 0..63 are I-type MBs; 64..127\n\
         /// are P-type. See spec/99 §3.1 for consumer semantics.\n\
         pub const MCBPCY_V3_RAW: &[(u32, u32)] = &[",
        alphabet_size, partition,
    )
    .unwrap();
    for &(bl, code) in &records[1..] {
        writeln!(f, "    ({bl}, {code}),").unwrap();
    }
    writeln!(f, "];").unwrap();
}
