//! Clean-room extracted table data loaded from `tables/*.csv` at build
//! time. **The Implementer must not retype these numbers manually** —
//! they come from the Extractor's dumps of
//! `reference/binaries/wmpcdcs8-2001/mpg4c32.dll` and are included via
//! `build.rs`. See `docs/video/msmpeg4/spec/99-current-understanding.md`
//! §8 for provenance.

// Generated by build.rs from `tables/region_05eac8.csv` — the v3
// joint-MCBPCY VLC source (per spec/99 §3.1 / §8.1). Defines:
//   - MCBPCY_V3_ALPHABET_SIZE: usize
//   - MCBPCY_V3_PARTITION: usize
//   - MCBPCY_V3_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
include!(concat!(env!("OUT_DIR"), "/mcbpcy_v3.rs"));

// Generated by build.rs from `tables/region_05bfc0.csv` — the v3
// joint (MVDx, MVDy) MV VLC source default variant (spec/06 §2.1,
// VMA 0x1c25cbc0). Defines:
//   - MV_V3_ALPHABET_SIZE: usize (= 1100)
//   - MV_V3_ESC_INDEX: usize (= 1099)
//   - MV_V3_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
include!(concat!(env!("OUT_DIR"), "/mv_v3.rs"));

// Generated by build.rs from `tables/region_05e228.hex` +
// `tables/region_05e678.hex` — MVDx / MVDy byte LUTs default variant
// (spec/06 §2.2, VMAs 0x1c25ee28 / 0x1c25f278). Defines:
//   - MVDX_V3_BYTES: &[u8; 1104]
//   - MVDY_V3_BYTES: &[u8; 1104]
include!(concat!(env!("OUT_DIR"), "/mv_lut_v3.rs"));

// Generated by build.rs from `tables/region_05eed0.csv` — candidate
// v3 intra AC TCOEF primary VLC source at VMA 0x1c25fad0 (file offset
// 0x5eed0). Role attribution is OPEN per spec/99 §0.1 row 8 (candidate
// intra-AC primary per spec/03 §5.3, alternative v2 MCBPCY source per
// spec/99 §9 OPEN-O6). The bytes are reproducibly extracted regardless
// and form a complete 64-entry canonical-Huffman prefix code (Kraft
// sum exactly 1, verified at build time). Defines:
//   - INTRA_AC_V3_CANDIDATE_ALPHABET: usize (= 64)
//   - INTRA_AC_V3_CANDIDATE_PARTITION: usize (= 1)
//   - INTRA_AC_V3_CANDIDATE_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
include!(concat!(env!("OUT_DIR"), "/intra_ac_v3.rs"));

// Generated by build.rs from `tables/region_053140.hex` — combined v1
// MCBPC (VMA 0x1c253d40, max-bitlen 9, 21 entries) + v2 MCBPC (VMA
// 0x1c254140, max-bitlen 7, 8 entries) tables. Per spec/07 §1.3 / §2.3.
// Defines:
//   - MCBPC_V1_RAW: &[(u8, u8, u32)] (sym, bit_length, canonical_code)
//   - MCBPC_V2_RAW: &[(u8, u8, u32)] (sym, bit_length, canonical_code)
include!(concat!(env!("OUT_DIR"), "/mcbpc_v1_v2.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mcbpcy_v3_header_matches_spec() {
        // Per spec/99 §3.1: 128-entry canonical-Huffman with partition 64.
        assert_eq!(MCBPCY_V3_ALPHABET_SIZE, 128);
        assert_eq!(MCBPCY_V3_PARTITION, 64);
        assert_eq!(MCBPCY_V3_RAW.len(), 128);
    }

    #[test]
    fn mcbpcy_v3_first_entry_from_csv() {
        // Sanity: the first payload entry in region_05eac8.csv is
        // (bit_length=7, code_value=5065). If build.rs ever mis-parses
        // the CSV columns, this test catches it.
        assert_eq!(MCBPCY_V3_RAW[0], (7, 5065));
    }

    #[test]
    fn mcbpcy_v3_bit_lengths_reasonable() {
        // Each bit_length ought to be in a canonical-Huffman-ish range.
        // The extractor's own histogram shows bl ∈ {0, 1, 3..21} roughly,
        // with a handful of non-monotonic entries. Assert the upper
        // bound loosely — catches catastrophic column swaps but doesn't
        // over-constrain the data.
        for (i, &(bl, _)) in MCBPCY_V3_RAW.iter().enumerate() {
            assert!(
                bl <= 32,
                "entry {i}: bit_length {bl} out of reasonable range — CSV \
                 parser may have swapped columns"
            );
        }
    }

    #[test]
    fn intra_ac_v3_candidate_header_matches_spec() {
        // region_05eed0.csv row 0 = (count_A=64, count_B=1) per the
        // packed header convention. 64 payload entries follow.
        assert_eq!(INTRA_AC_V3_CANDIDATE_ALPHABET, 64);
        assert_eq!(INTRA_AC_V3_CANDIDATE_PARTITION, 1);
        assert_eq!(INTRA_AC_V3_CANDIDATE_RAW.len(), 64);
    }

    #[test]
    fn intra_ac_v3_candidate_first_entry_from_csv() {
        // Sanity: row 1 of region_05eed0.csv is (symbol_dec=1,
        // bit_length=23) — under the build.rs swap convention this
        // is (bit_length=1, code_value=23). Catches column swaps.
        assert_eq!(INTRA_AC_V3_CANDIDATE_RAW[0], (1, 23));
    }

    #[test]
    fn intra_ac_v3_candidate_kraft_sum_is_one() {
        // Repeat the build-time check at runtime so tests fail loudly
        // if the CSV data ever drifts. Sum of 2^-bl == 1 iff sum of
        // 2^(MAX-bl) == 2^MAX with MAX=32.
        let max_bl: u32 = 32;
        let target: u64 = 1u64 << max_bl;
        let mut sum: u64 = 0;
        for &(bl, _) in INTRA_AC_V3_CANDIDATE_RAW {
            assert!((1..=32).contains(&bl), "bit_length {bl} out of valid range");
            sum += 1u64 << (max_bl - bl);
        }
        assert_eq!(
            sum, target,
            "Kraft sum != 1 — table is not a complete prefix code"
        );
    }

    #[test]
    fn intra_ac_v3_candidate_bit_lengths_in_range() {
        // Per spec/99 §3.4 the shared canonical-Huffman walker has a
        // primary pre-expansion of 8 bits and up to 2 refill tiers, so
        // bit-lengths up to 24 are plausible. Empirically this table
        // ranges 1..=13.
        for (i, &(bl, _)) in INTRA_AC_V3_CANDIDATE_RAW.iter().enumerate() {
            assert!(
                (1..=24).contains(&bl),
                "entry {i}: bit_length {bl} outside [1, 24]"
            );
        }
    }

    #[test]
    fn mcbpc_v1_alphabet_matches_spec() {
        // Per spec/07 §1.3: 21 entries, sym 0..=20, max bit-length 9.
        // Build-time Kraft check accounts for the all-zero-9bit sentinel.
        assert_eq!(MCBPC_V1_RAW.len(), 21);
        let symbols: Vec<u8> = MCBPC_V1_RAW.iter().map(|&(s, _, _)| s).collect();
        assert_eq!(
            symbols,
            (0..=20u8).collect::<Vec<u8>>(),
            "expected contiguous symbols 0..=20"
        );
        for &(_, bl, _) in MCBPC_V1_RAW {
            assert!((1..=9).contains(&bl), "v1 MCBPC bl={bl} out of [1,9]");
        }
    }

    #[test]
    fn mcbpc_v2_alphabet_matches_spec() {
        // Per spec/07 §2.3: 8 entries, sym 0..=7, max bit-length 7.
        assert_eq!(MCBPC_V2_RAW.len(), 8);
        let symbols: Vec<u8> = MCBPC_V2_RAW.iter().map(|&(s, _, _)| s).collect();
        assert_eq!(
            symbols,
            (0..=7u8).collect::<Vec<u8>>(),
            "expected contiguous symbols 0..=7"
        );
        for &(_, bl, _) in MCBPC_V2_RAW {
            assert!((1..=7).contains(&bl), "v2 MCBPC bl={bl} out of [1,7]");
        }
    }

    #[test]
    fn mcbpc_v1_is_prefix_free() {
        // Canonical-Huffman invariant: no entry's code is a prefix of
        // any other entry's code. The 21-entry alphabet plus the all-
        // zero-9bit sentinel together fill the 9-bit code space exactly.
        for (i, &(_, bla, ca)) in MCBPC_V1_RAW.iter().enumerate() {
            for (j, &(_, blb, cb)) in MCBPC_V1_RAW.iter().enumerate() {
                if i == j || bla == blb {
                    continue;
                }
                let (short_bl, short_c, long_bl, long_c) = if bla < blb {
                    (bla, ca, blb, cb)
                } else {
                    (blb, cb, bla, ca)
                };
                let shift = long_bl - short_bl;
                let long_prefix = long_c >> shift;
                assert_ne!(
                    long_prefix, short_c,
                    "v1 MCBPC: code 0x{short_c:x} (bl {short_bl}) is a prefix of 0x{long_c:x} (bl {long_bl})"
                );
            }
        }
    }

    #[test]
    fn mcbpc_v2_is_prefix_free() {
        for (i, &(_, bla, ca)) in MCBPC_V2_RAW.iter().enumerate() {
            for (j, &(_, blb, cb)) in MCBPC_V2_RAW.iter().enumerate() {
                if i == j || bla == blb {
                    continue;
                }
                let (short_bl, short_c, long_bl, long_c) = if bla < blb {
                    (bla, ca, blb, cb)
                } else {
                    (blb, cb, bla, ca)
                };
                let shift = long_bl - short_bl;
                let long_prefix = long_c >> shift;
                assert_ne!(
                    long_prefix, short_c,
                    "v2 MCBPC: code 0x{short_c:x} (bl {short_bl}) is a prefix of 0x{long_c:x} (bl {long_bl})"
                );
            }
        }
    }

    #[test]
    fn mcbpc_v2_kraft_sum_is_one() {
        // Confirm v2's prefix code is a complete cover (Kraft = 1.0).
        let max_bl: u32 = 32;
        let target: u64 = 1u64 << max_bl;
        let sum: u64 = MCBPC_V2_RAW
            .iter()
            .map(|&(_, bl, _)| 1u64 << (max_bl - bl as u32))
            .sum();
        assert_eq!(sum, target);
    }
}
