//! Clean-room extracted table data loaded from `tables/*.csv` at build
//! time. **The Implementer must not retype these numbers manually** —
//! they come from the Extractor's dumps of
//! `reference/binaries/wmpcdcs8-2001/mpg4c32.dll` and are included via
//! `build.rs`. See `docs/video/msmpeg4/spec/99-current-understanding.md`
//! §8 for provenance.

// Generated by build.rs from `tables/region_05eac8.csv` — the v3
// joint-MCBPCY VLC source (per spec/99 §3.1 / §8.1). Defines:
//   - MCBPCY_V3_ALPHABET_SIZE: usize
//   - MCBPCY_V3_PARTITION: usize
//   - MCBPCY_V3_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
include!(concat!(env!("OUT_DIR"), "/mcbpcy_v3.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mcbpcy_v3_header_matches_spec() {
        // Per spec/99 §3.1: 128-entry canonical-Huffman with partition 64.
        assert_eq!(MCBPCY_V3_ALPHABET_SIZE, 128);
        assert_eq!(MCBPCY_V3_PARTITION, 64);
        assert_eq!(MCBPCY_V3_RAW.len(), 128);
    }

    #[test]
    fn mcbpcy_v3_first_entry_from_csv() {
        // Sanity: the first payload entry in region_05eac8.csv is
        // (bit_length=7, code_value=5065). If build.rs ever mis-parses
        // the CSV columns, this test catches it.
        assert_eq!(MCBPCY_V3_RAW[0], (7, 5065));
    }

    #[test]
    fn mcbpcy_v3_bit_lengths_reasonable() {
        // Each bit_length ought to be in a canonical-Huffman-ish range.
        // The extractor's own histogram shows bl ∈ {0, 1, 3..21} roughly,
        // with a handful of non-monotonic entries. Assert the upper
        // bound loosely — catches catastrophic column swaps but doesn't
        // over-constrain the data.
        for (i, &(bl, _)) in MCBPCY_V3_RAW.iter().enumerate() {
            assert!(
                bl <= 32,
                "entry {i}: bit_length {bl} out of reasonable range — CSV \
                 parser may have swapped columns"
            );
        }
    }
}
