//! Clean-room extracted table data loaded from `tables/*.csv` at build
//! time. **The Implementer must not retype these numbers manually** —
//! they come from the Extractor's dumps of
//! `reference/binaries/wmpcdcs8-2001/mpg4c32.dll` and are included via
//! `build.rs`. See `docs/video/msmpeg4/spec/99-current-understanding.md`
//! §8 for provenance.

// Generated by build.rs from `tables/region_05eac8_mcbpcy.csv` — the
// v3 joint-MCBPCY VLC source (per spec/99 §3.1 / §8.1 and
// provenance/22 / Extractor 08, VMA 0x1c25f6c8). Defines:
//   - MCBPCY_V3_ALPHABET_SIZE: usize (= 128)
//   - MCBPCY_V3_PARTITION: usize (= 64; from patent US 6,563,953
//     Table 1 / audit/02 §1.4, not the wire table)
//   - MCBPCY_V3_RAW: &[(u32, u32)] of (bit_length, code) pairs, where
//     `code` is the actual DLL wire bit-pattern consumed verbatim by
//     the runtime decoder (provenance/22; NOT a canonical
//     reconstruction — canonical matched the real codes 0/128).
include!(concat!(env!("OUT_DIR"), "/mcbpcy_v3.rs"));

// Generated by build.rs from `tables/region_05bfc0_mvvlc.csv` — the v3
// joint (MVDx, MVDy) MV VLC source default variant (spec/16 §1 /
// Extractor 07, VMA 0x1c25cbc0). Defines:
//   - MV_V3_ALPHABET_SIZE: usize (= 1100)
//   - MV_V3_ESC_INDEX: usize (= 1099)
//   - MV_V3_RAW: &[(u32, u32)] of (bit_length, code) pairs, where `code`
//     is the actual DLL wire bit-pattern consumed verbatim by the
//     runtime decoder (spec/12 §2; NOT a canonical reconstruction).
include!(concat!(env!("OUT_DIR"), "/mv_v3.rs"));

// Generated by build.rs from `tables/region_05e228.hex` +
// `tables/region_05e678.hex` — MVDx / MVDy byte LUTs default variant
// (spec/06 §2.2, VMAs 0x1c25ee28 / 0x1c25f278). Defines:
//   - MVDX_V3_BYTES: &[u8; 1104]
//   - MVDY_V3_BYTES: &[u8; 1104]
include!(concat!(env!("OUT_DIR"), "/mv_lut_v3.rs"));

// Generated by build.rs from `tables/region_05b720.hex` +
// `tables/region_05bb70.hex` — MVDx / MVDy byte LUTs alternate variant
// (spec/06 §2.2, VMAs 0x1c25c320 / 0x1c25c770). These pair with the
// alternate joint MV VLC at VMA 0x1c25a0b8 (selector
// `mv_table_sel == 1`). The VLC source extraction itself is currently
// a 256-byte truncation of the 8804-byte spec/11 §5 region — these
// byte LUTs are landed in advance so wiring the alt VLC path is a
// single-emitter swap once the source is re-extracted. Defines:
//   - MVDX_V3_ALT_BYTES: &[u8; 1104]
//   - MVDY_V3_ALT_BYTES: &[u8; 1104]
include!(concat!(env!("OUT_DIR"), "/mv_lut_v3_alt.rs"));

// Generated by build.rs from `tables/region_0594b8_mvvlc.csv` — the v3
// joint (MVDx, MVDy) MV VLC source ALTERNATE variant (spec/16 §1 /
// Extractor 07, VMA 0x1c25a0b8, file 0x594b8). Selected by the
// per-frame `mv_table_sel == 1` bit. The full 8804-byte re-extraction
// (1100 entries, ESC at 1099, Kraft = 1.0) supersedes the earlier
// 256-byte truncation. Defines:
//   - MV_V3_ALT_RAW: &[(u32, u32)] of (bit_length, code) pairs, where
//     `code` is the actual DLL wire bit-pattern consumed verbatim by the
//     runtime decoder (spec/12 §2; NOT a canonical reconstruction).
include!(concat!(env!("OUT_DIR"), "/mv_v3_alt.rs"));

// Generated by build.rs from `tables/region_05eed0.csv` — candidate
// v3 intra AC TCOEF primary VLC source at VMA 0x1c25fad0 (file offset
// 0x5eed0). Role attribution is OPEN per spec/99 §0.1 row 8 (candidate
// intra-AC primary per spec/03 §5.3, alternative v2 MCBPCY source per
// spec/99 §9 OPEN-O6). The bytes are reproducibly extracted regardless
// and form a complete 64-entry canonical-Huffman prefix code (Kraft
// sum exactly 1, verified at build time). Defines:
//   - INTRA_AC_V3_CANDIDATE_ALPHABET: usize (= 64)
//   - INTRA_AC_V3_CANDIDATE_PARTITION: usize (= 1)
//   - INTRA_AC_V3_CANDIDATE_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
include!(concat!(env!("OUT_DIR"), "/intra_ac_v3.rs"));

// Generated by build.rs from `tables/region_053140.hex` — combined v1
// MCBPC (VMA 0x1c253d40, max-bitlen 9, 21 entries) + v2 MCBPC (VMA
// 0x1c254140, max-bitlen 7, 8 entries) tables. Per spec/07 §1.3 / §2.3.
// Defines:
//   - MCBPC_V1_RAW: &[(u8, u8, u32)] (sym, bit_length, canonical_code)
//   - MCBPC_V2_RAW: &[(u8, u8, u32)] (sym, bit_length, canonical_code)
include!(concat!(env!("OUT_DIR"), "/mcbpc_v1_v2.rs"));

// Generated by build.rs from `tables/region_053640.hex` — shared v1/v2
// CBPY VLC at VMA 0x1c254240 (per spec/07 §1.3 / §2.3, helper 0x1c215811
// with max-bitlen 6, 16-entry alphabet + 2 reserved-sentinel symbols).
// Cross-checked at build time against the H.263 Table 8 / MPEG-4 Part 2
// Table B-6 values that ship in src/tables.rs::CBPY_INTRA_TABLE — the
// build breaks if the binary's pre-expanded LUT ever drifts from the
// public-standard CBPY codes. Defines:
//   - CBPY_V1_V2_RAW: &[(u8, u8, u32)] of (sym, bit_length, canonical_code)
//     for the 16-symbol CBPY alphabet (one entry per CBPY pattern 0..=15)
//   - CBPY_V1_V2_SENTINELS: &[(u8, u8, u32)] for the 2 reserved-sentinel
//     symbols (0x10, 0x11) at the all-zero and `000001` 6-bit windows;
//     the runtime decoder rejects raw > 15 via `decode_cbpy_with_wrap`'s
//     range check, so these surface as bitstream errors.
include!(concat!(env!("OUT_DIR"), "/cbpy_v1_v2.rs"));

// Generated by build.rs from `tables/region_04ed30_full.hex` — v1/v2
// per-component MV VLC table (VMA 0x1c24f930, max-bitlen 13, 65 entries).
// Per spec/06 §2.3 / spec/07 §3 the same table is used twice (once per
// MV axis). Defines:
//   - MV_V1_V2_ALPHABET_SIZE: usize (= 65)
//   - MV_V1_V2_BIAS: i32 (= 32 — subtract from raw idx to recover signed MVD residual)
//   - MV_V1_V2_RAW: &[(u8, u8, u32)] (sym, bit_length, canonical_code)
include!(concat!(env!("OUT_DIR"), "/mv_v1_v2.rs"));

// Generated by build.rs from `tables/region_0542c0_dcsize.csv` (luma,
// VMA 0x1c2542c0) and `tables/region_0543c0_dcsize.csv` (chroma, VMA
// 0x1c2543c0) — the v1/v2 intra (I-frame) DC-size category VLCs, per
// spec/16 §2 (Extractor 07). MS-MPEG4 v1 and v2 SHARE the H.263 §5.4.1
// / MPEG-4 Part 2 §7.4.3 DC-size-then-value intra-DC coding (the
// intra-block driver gates `cmp [esi+8],3`: v<3 → sub_15790 with these
// two size tables). This is distinct from v3's direct-value DC VLC and
// has nothing to do with the v3 `dc_size_sel` 4-table selection.
// Defines:
//   - DC_SIZE_LUMA_V1V2_RAW:   &[(u8, u8, u32)] (size_category, bit_length, canonical_code)
//   - DC_SIZE_CHROMA_V1V2_RAW: &[(u8, u8, u32)] for the 9 size categories 0..=8
include!(concat!(env!("OUT_DIR"), "/dc_size_luma_v1v2.rs"));
include!(concat!(env!("OUT_DIR"), "/dc_size_chroma_v1v2.rs"));

// Generated by build.rs from `tables/region_053140_mbtype.csv` — the
// authoritative per-symbol MB-type info for the 21-symbol v1 P-frame
// MCBPC alphabet (Extractor 07 / spec/16 §3). Pins the INTER4V (MB-type
// 2) 4-MV mode and the INTRA / INTRA+Q (MB-types 3, 4) intra
// classification at value level. Defines:
//   - MB_TYPE_V1_INFO: [(u8, bool, u8); 21]
//       index = MCBPC symbol 0..=20; tuple = (mb_type, is_intra,
//       num_motion_vectors). Symbol 20 = STUFFING/ESC (mb_type = 0xff).
include!(concat!(env!("OUT_DIR"), "/mbtype_v1.rs"));

// Generated by build.rs from `tables/region_0569c0.hex` (cluster region) +
// `tables/region_057898.hex` (G5 pri_B gap fill, round 19) — the
// G-descriptor pri_A / pri_B set for groups G4 (chroma + all-inter) and
// G5 (intra-luma). Per spec/99 §5 / audit/01 §3 / §4. Defines:
//   - G4_COUNT_A: usize (= 102), G4_COUNT_B: usize (= 57)
//   - G5_COUNT_A: usize (= 102), G5_COUNT_B: usize (= 66)
//   - G4_PRI_A: &[u8; 102]   |level| per symbol (sub-A 0..=57, sub-B 58..=101)
//   - G4_PRI_B: &[u8; 102]   run per symbol (low byte of u32-LE; upper 24 b zero)
//   - G5_PRI_A: &[u8; 102]   |level| per symbol
//   - G5_PRI_B: &[u8; 102]   run per symbol (sub-A 0..=66, sub-B 67..=101)
include!(concat!(env!("OUT_DIR"), "/g_descriptors.rs"));

// Generated by build.rs from `tables/region_058e38_full.hex` and
// `tables/region_059178_full.hex` — the G4 (inter chroma + all-inter) and
// G5 (intra-luma) PRIMARY canonical-Huffman VLC sources for the DCT AC
// TCOEF walk, per docs/video/msmpeg4/spec/11-walker-format-resolved.md §3-§7.
// Each is a 103-entry `(bit_length, code_value)` array; idx 102 is ESC
// (Kraft sum = 1 - 2/1024). The canonical bit-pattern is reconstructed
// from the bit_length array alone via the standard MSB-first canonical
// Huffman builder; the consumer maps the decoded idx through
// `g_descriptor::g{4,5}_decode` to recover (last, run, |level|) or ESC.
//
// Defines:
//   - G4_PRIMARY_ALPHABET: usize (= 103), G4_PRIMARY_ESC_INDEX: usize (= 102)
//   - G4_PRIMARY_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
//   - G5_PRIMARY_ALPHABET: usize (= 103), G5_PRIMARY_ESC_INDEX: usize (= 102)
//   - G5_PRIMARY_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
include!(concat!(env!("OUT_DIR"), "/g4_primary.rs"));
include!(concat!(env!("OUT_DIR"), "/g5_primary.rs"));

// Generated by build.rs from `tables/region_05{7a30,7f80,8558,8a08}_full.hex` —
// the G0..G3 (extended-alphabet) PRIMARY canonical-Huffman VLC sources for the
// DCT AC TCOEF walk, per docs/video/msmpeg4/spec/11-walker-format-resolved.md
// §3-§5 row 1-4. Same `(code, bl)` record format as G4/G5 but different
// alphabet shapes per spec/15 §3 and Kraft sum exactly 1 (no reserved ESC
// codeword — the ESC entry occupies a regular bit-length slot at
// idx == count_A per spec/09 §2).
//
// Each include emits:
//   - G<N>_PRIMARY_ALPHABET: usize
//   - G<N>_PRIMARY_ESC_INDEX: usize (== count_A)
//   - G<N>_PRIMARY_RAW: &[(u32, u32)] of (bit_length, code_value) pairs
//
// | G  | count | ESC idx | max_bl | file off | VMA       |
// | -- | ----- | ------- | ------ | -------- | --------- |
// | G0 | 169   | 168     | 15     | 0x57a30  | 0x1c258630 |
// | G1 | 186   | 185     | 15     | 0x57f80  | 0x1c258b80 |
// | G2 | 149   | 148     | 15     | 0x58558  | 0x1c259158 |
// | G3 | 133   | 132     | 13     | 0x58a08  | 0x1c259608 |
include!(concat!(env!("OUT_DIR"), "/g0_primary.rs"));
include!(concat!(env!("OUT_DIR"), "/g1_primary.rs"));
include!(concat!(env!("OUT_DIR"), "/g2_primary.rs"));
include!(concat!(env!("OUT_DIR"), "/g3_primary.rs"));

// Generated by build.rs from `tables/region_<addr>_g<N>_enum.csv` —
// the per-symbol (run, level_mag, last) enumeration of the four extended
// G-descriptor alphabets G0..G3, per
// `docs/video/msmpeg4/spec/09-g0-g3-enumeration.md` and round-29
// extractor session 06 (`tables/extract-06.sh`).
//
// Each table has length `count_A`. Index in the array == primary-VLC
// symbol index. The ESC sentinel is at idx == count_A and is NOT stored
// in the array (callers test the boundary explicitly per spec/04 §1.3
// step 3 and spec/13 §2).
//
// | G | count_A | count_B | csv |
// | - | ------- | ------- | --- |
// | G0 | 168 | 98  | region_056c60_g0_enum.csv |
// | G1 | 185 | 118 | region_056ff0_g1_enum.csv |
// | G2 | 148 | 80  | region_057300_g2_enum.csv |
// | G3 | 132 | 84  | region_0575a8_g3_enum.csv |
include!(concat!(env!("OUT_DIR"), "/g0_enum.rs"));
include!(concat!(env!("OUT_DIR"), "/g1_enum.rs"));
include!(concat!(env!("OUT_DIR"), "/g2_enum.rs"));
include!(concat!(env!("OUT_DIR"), "/g3_enum.rs"));

// Generated by build.rs from `tables/region_060988.hex` +
// `tables/region_060988_index.csv` (round 33) — the 24-slice ESC
// extension table cluster (file 0x60988..0x61200, VMA 0x1c261588..
// 0x1c261e00, 2168 bytes). Per `docs/video/msmpeg4/spec/08-descriptor-
// constants.md` §1 / §2 each G-descriptor's `+0x0c..+0x18` pointer
// block addresses four of the slices: sub-A level-extension, sub-B
// level-extension (`+0x0c / +0x10`, byte arrays read at stride 4),
// and sub-A run-extension, sub-B run-extension (`+0x14 / +0x18`, u32
// arrays at stride 4). The kernel reads these only on first-tier and
// second-tier ESC paths; the general-path dequant uses
// `[esi+0x13c] / [esi+0x140]` (PQUANT-derived) per `spec/07` §4.1 and
// `spec/08` §1.3.
//
// Defines:
//   - ESC_EXT_SLICE_COUNT: usize (= 24)
//   - ESC_EXT_CLUSTER_BYTES: usize (= 2168)
//   - ESC_EXT_SLICE_<i>: &[u8] for i in 0..24 (slice in CSV order)
//   - ESC_EXT_SLICES: [&[u8]; 24]
//   - ESC_EXT_SLICE_META: [(usize relative_offset, u32 vma, usize length); 24]
//   - ESC_EXT_G{0,1,2,3,4,5}_SLICE_INDICES: [usize; 4]
//     (the four cluster-slice indices that match each G-descriptor's
//     `(+0x0c, +0x10, +0x14, +0x18)` pointer block per `spec/08` §2.2 /
//     `spec/14` §2.1)
//
// **Slice-content semantics remain spec-OPEN per `spec/08` §4.1.** The
// kernel reads `[base + idx*4]` (BYTE for `+0x0c/+0x10`, DWORD for
// `+0x14/+0x18`) but the slices' record format is mechanically
// `(symbol_u32_le, bit_length_u32_le)` 8-byte pairs; the relationship
// between the two — and whether the slices are themselves secondary
// canonical-Huffman sources — is not yet pinned down. Round 33 wires
// the bytes and per-descriptor attribution only.
include!(concat!(env!("OUT_DIR"), "/esc_ext_cluster.rs"));

// Generated by build.rs from the in-source `G_COUNTS_SPEC15` table
// (build.rs top-of-file). Carries the spec/15 §3 authoritative per-G
// `(count_A, count_B)` tuples for the six MS-MPEG4 DCT-AC G-descriptors
// (G0..G5), plus the derived `(sub_A_size, sub_B_size)` partition
// arithmetic per spec/03 §4.4 / spec/15 §5.2.
//
// Defines:
//   - G_COUNTS_SPEC15: [(u32, u32); 6]   (count_A, count_B) per G
//   - G_SUBCLASS_SIZES_SPEC15: [(u32, u32); 6]   (sub_A, sub_B) per G
//
// FROM: `docs/video/msmpeg4/spec/15-count-ab-per-g-family.md` §3 (binary)
// FROM: constructor disassembly `mb_mv_struct_init` at VMA `0x1c210643`
//       in mpg4c32.dll (SHA-256 aedb4cf3...b3c099).
include!(concat!(env!("OUT_DIR"), "/g_counts.rs"));

// Generated by build.rs from `tables/region_05f0d8.hex` /
// `region_05f4a0.hex` / `region_05f868.hex` / `region_05fc30.hex` —
// MS-MPEG4 v3 intra-DC custom direct-value VLCs, per
// `docs/video/msmpeg4/spec/07-remaining-opens.md` §5.4 +
// `docs/video/msmpeg4/spec/99-current-understanding.md` §4.5.
//
// Each table has 120 canonical-Huffman entries; the decoded `idx` is
// directly the DC-differential magnitude (idx 0 → diff=0 with no sign
// bit; idx ∈ [1, 118] → ±idx with a separately-read sign bit; idx == 119
// → ESC, read 8-bit raw value + sign bit). The picture-header
// `dc_size_sel` bit picks between the `_SEL0` and `_SEL1` pairs. Defines:
//   - INTRA_DC_LUMA_SEL0_RAW / _ALPHABET / _ESC_INDEX
//   - INTRA_DC_CHROMA_SEL0_RAW / _ALPHABET / _ESC_INDEX
//   - INTRA_DC_LUMA_SEL1_RAW / _ALPHABET / _ESC_INDEX
//   - INTRA_DC_CHROMA_SEL1_RAW / _ALPHABET / _ESC_INDEX
include!(concat!(env!("OUT_DIR"), "/intra_dc_luma_sel0.rs"));
include!(concat!(env!("OUT_DIR"), "/intra_dc_chroma_sel0.rs"));
include!(concat!(env!("OUT_DIR"), "/intra_dc_luma_sel1.rs"));
include!(concat!(env!("OUT_DIR"), "/intra_dc_chroma_sel1.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mcbpcy_v3_header_matches_spec() {
        // Per spec/99 §3.1 / provenance/22: 128-entry complete prefix
        // code; partition 64 per patent Table 1 (audit/02 §1.4).
        assert_eq!(MCBPCY_V3_ALPHABET_SIZE, 128);
        assert_eq!(MCBPCY_V3_PARTITION, 64);
        assert_eq!(MCBPCY_V3_RAW.len(), 128);
    }

    #[test]
    fn mcbpcy_v3_spot_entries_from_csv() {
        // Sanity spot-checks against literal rows of
        // region_05eac8_mcbpcy.csv (provenance/22): symbol 0 is
        // (code=64=0b1000000, bit_length=7) — the record whose code the
        // retired mis-parse read as a second header field — and symbols
        // 1/2 are (5065, 13) / (2557, 12). MCBPCY_V3_RAW stores
        // (bit_length, code). If build.rs ever mis-parses the CSV
        // columns, this catches it.
        assert_eq!(MCBPCY_V3_RAW[0], (7, 64));
        assert_eq!(MCBPCY_V3_RAW[1], (13, 5065));
        assert_eq!(MCBPCY_V3_RAW[2], (12, 2557));
    }

    #[test]
    fn mcbpcy_v3_codes_fit_and_lengths_in_meta_span() {
        // The .meta pins bit_length ∈ [2, 21] and `codes_fit_length`.
        // Assert both — catches column swaps and truncated rows.
        for (i, &(bl, code)) in MCBPCY_V3_RAW.iter().enumerate() {
            assert!(
                (2..=21).contains(&bl),
                "entry {i}: bit_length {bl} outside the .meta span [2, 21]"
            );
            assert!(
                u64::from(code) < (1u64 << bl),
                "entry {i}: code {code} does not fit bit_length {bl}"
            );
        }
    }

    #[test]
    fn mcbpcy_v3_kraft_sum_is_exactly_one() {
        // provenance/22 acceptance test: Kraft sum over all 128
        // (code, bit_length) records = exactly 1.0 → complete prefix
        // code. Fixed-point against 2^max_bl.
        let max_bl = MCBPCY_V3_RAW.iter().map(|&(bl, _)| bl).max().unwrap();
        let num: u64 = MCBPCY_V3_RAW
            .iter()
            .map(|&(bl, _)| 1u64 << (max_bl - bl))
            .sum();
        assert_eq!(num, 1u64 << max_bl, "Kraft sum != 1.0");
    }

    #[test]
    fn intra_ac_v3_candidate_header_matches_spec() {
        // region_05eed0.csv row 0 = (count_A=64, count_B=1) per the
        // packed header convention. 64 payload entries follow.
        assert_eq!(INTRA_AC_V3_CANDIDATE_ALPHABET, 64);
        assert_eq!(INTRA_AC_V3_CANDIDATE_PARTITION, 1);
        assert_eq!(INTRA_AC_V3_CANDIDATE_RAW.len(), 64);
    }

    #[test]
    fn intra_ac_v3_candidate_first_entry_from_csv() {
        // Sanity: row 1 of region_05eed0.csv is (symbol_dec=1,
        // bit_length=23) — under the build.rs swap convention this
        // is (bit_length=1, code_value=23). Catches column swaps.
        assert_eq!(INTRA_AC_V3_CANDIDATE_RAW[0], (1, 23));
    }

    #[test]
    fn intra_ac_v3_candidate_kraft_sum_is_one() {
        // Repeat the build-time check at runtime so tests fail loudly
        // if the CSV data ever drifts. Sum of 2^-bl == 1 iff sum of
        // 2^(MAX-bl) == 2^MAX with MAX=32.
        let max_bl: u32 = 32;
        let target: u64 = 1u64 << max_bl;
        let mut sum: u64 = 0;
        for &(bl, _) in INTRA_AC_V3_CANDIDATE_RAW {
            assert!((1..=32).contains(&bl), "bit_length {bl} out of valid range");
            sum += 1u64 << (max_bl - bl);
        }
        assert_eq!(
            sum, target,
            "Kraft sum != 1 — table is not a complete prefix code"
        );
    }

    #[test]
    fn intra_ac_v3_candidate_bit_lengths_in_range() {
        // Per spec/99 §3.4 the shared canonical-Huffman walker has a
        // primary pre-expansion of 8 bits and up to 2 refill tiers, so
        // bit-lengths up to 24 are plausible. Empirically this table
        // ranges 1..=13.
        for (i, &(bl, _)) in INTRA_AC_V3_CANDIDATE_RAW.iter().enumerate() {
            assert!(
                (1..=24).contains(&bl),
                "entry {i}: bit_length {bl} outside [1, 24]"
            );
        }
    }

    #[test]
    fn mcbpc_v1_alphabet_matches_spec() {
        // Per spec/07 §1.3: 21 entries, sym 0..=20, max bit-length 9.
        // Build-time Kraft check accounts for the all-zero-9bit sentinel.
        assert_eq!(MCBPC_V1_RAW.len(), 21);
        let symbols: Vec<u8> = MCBPC_V1_RAW.iter().map(|&(s, _, _)| s).collect();
        assert_eq!(
            symbols,
            (0..=20u8).collect::<Vec<u8>>(),
            "expected contiguous symbols 0..=20"
        );
        for &(_, bl, _) in MCBPC_V1_RAW {
            assert!((1..=9).contains(&bl), "v1 MCBPC bl={bl} out of [1,9]");
        }
    }

    #[test]
    fn mcbpc_v2_alphabet_matches_spec() {
        // Per spec/07 §2.3: 8 entries, sym 0..=7, max bit-length 7.
        assert_eq!(MCBPC_V2_RAW.len(), 8);
        let symbols: Vec<u8> = MCBPC_V2_RAW.iter().map(|&(s, _, _)| s).collect();
        assert_eq!(
            symbols,
            (0..=7u8).collect::<Vec<u8>>(),
            "expected contiguous symbols 0..=7"
        );
        for &(_, bl, _) in MCBPC_V2_RAW {
            assert!((1..=7).contains(&bl), "v2 MCBPC bl={bl} out of [1,7]");
        }
    }

    #[test]
    fn mcbpc_v1_is_prefix_free() {
        // Canonical-Huffman invariant: no entry's code is a prefix of
        // any other entry's code. The 21-entry alphabet plus the all-
        // zero-9bit sentinel together fill the 9-bit code space exactly.
        for (i, &(_, bla, ca)) in MCBPC_V1_RAW.iter().enumerate() {
            for (j, &(_, blb, cb)) in MCBPC_V1_RAW.iter().enumerate() {
                if i == j || bla == blb {
                    continue;
                }
                let (short_bl, short_c, long_bl, long_c) = if bla < blb {
                    (bla, ca, blb, cb)
                } else {
                    (blb, cb, bla, ca)
                };
                let shift = long_bl - short_bl;
                let long_prefix = long_c >> shift;
                assert_ne!(
                    long_prefix, short_c,
                    "v1 MCBPC: code 0x{short_c:x} (bl {short_bl}) is a prefix of 0x{long_c:x} (bl {long_bl})"
                );
            }
        }
    }

    #[test]
    fn mcbpc_v2_is_prefix_free() {
        for (i, &(_, bla, ca)) in MCBPC_V2_RAW.iter().enumerate() {
            for (j, &(_, blb, cb)) in MCBPC_V2_RAW.iter().enumerate() {
                if i == j || bla == blb {
                    continue;
                }
                let (short_bl, short_c, long_bl, long_c) = if bla < blb {
                    (bla, ca, blb, cb)
                } else {
                    (blb, cb, bla, ca)
                };
                let shift = long_bl - short_bl;
                let long_prefix = long_c >> shift;
                assert_ne!(
                    long_prefix, short_c,
                    "v2 MCBPC: code 0x{short_c:x} (bl {short_bl}) is a prefix of 0x{long_c:x} (bl {long_bl})"
                );
            }
        }
    }

    #[test]
    fn mcbpc_v2_kraft_sum_is_one() {
        // Confirm v2's prefix code is a complete cover (Kraft = 1.0).
        let max_bl: u32 = 32;
        let target: u64 = 1u64 << max_bl;
        let sum: u64 = MCBPC_V2_RAW
            .iter()
            .map(|&(_, bl, _)| 1u64 << (max_bl - bl as u32))
            .sum();
        assert_eq!(sum, target);
    }

    // ---- G4 / G5 pri_A / pri_B (round 18) ----

    #[test]
    fn g4_dimensions_match_spec() {
        // spec/99 §5 row G4: count_A = 102, count_B = 57.
        assert_eq!(G4_COUNT_A, 102);
        assert_eq!(G4_COUNT_B, 57);
        assert_eq!(G4_PRI_A.len(), 102);
        assert_eq!(G4_PRI_B.len(), 102);
    }

    #[test]
    fn g5_dimensions_match_spec() {
        // spec/99 §5 row G5: count_A = 102, count_B = 66.
        assert_eq!(G5_COUNT_A, 102);
        assert_eq!(G5_COUNT_B, 66);
        assert_eq!(G5_PRI_A.len(), 102);
        // Round 19: G5 pri_B is fully wired from region_057898.hex.
        assert_eq!(G5_PRI_B.len(), 102);
    }

    #[test]
    fn g4_pri_a_canonical_level_prefix() {
        // audit/01 §2.2: G4 idx 0..11 are (run=0, level=1..12).
        for (i, &b) in G4_PRI_A.iter().enumerate().take(12) {
            assert_eq!(b, (i + 1) as u8, "G4 pri_A[{i}]");
        }
    }

    #[test]
    fn g4_pri_b_run_zero_prefix() {
        // run=0 entries occupy idx 0..11 (LMAX(0)=12 for inter).
        for (i, &v) in G4_PRI_B.iter().enumerate().take(12) {
            assert_eq!(v, 0, "G4 pri_B[{i}]");
        }
    }

    #[test]
    fn g4_partition_matches_audit_table() {
        // audit/01 §2.2: at idx=count_B=57, sub-A's last (run=26, level=1).
        // At idx=count_B+1=58, sub-B's first (run=0, level=1).
        assert_eq!(G4_PRI_A[G4_COUNT_B], 1, "sub-A last level");
        assert_eq!(G4_PRI_B[G4_COUNT_B], 26, "sub-A last run");
        assert_eq!(G4_PRI_A[G4_COUNT_B + 1], 1, "sub-B first level");
        assert_eq!(G4_PRI_B[G4_COUNT_B + 1], 0, "sub-B first run");
    }

    #[test]
    fn g4_pri_a_max_level_at_run_zero_is_12() {
        // Per audit/01 §3.3 LMAX(0) = 12 for inter. The G4 pri_A's
        // overall max should also be 12 (bigger levels would exceed
        // ESCL(b) limits for the lowest run).
        assert_eq!(*G4_PRI_A.iter().max().unwrap(), 12);
    }

    #[test]
    fn g4_pri_a_no_zero_no_sentinel() {
        // audit/01 §2.3: no entry has pri_A == 0 or 0xff.
        for &b in G4_PRI_A {
            assert_ne!(b, 0, "G4 pri_A contains zero — table corrupt");
            assert_ne!(b, 0xff, "G4 pri_A contains 0xff sentinel — wrong slice");
        }
    }

    #[test]
    fn g4_pri_b_max_run_is_40() {
        // audit/01 §2.2: sub-B last entry idx 101 has run=40.
        assert_eq!(G4_PRI_B[101], 40);
        assert_eq!(*G4_PRI_B.iter().max().unwrap(), 40);
    }

    #[test]
    fn g5_pri_a_canonical_level_prefix() {
        // audit/01 §4.1: G5 idx 0..26 are (run=0, level=1..27).
        for (i, &b) in G5_PRI_A.iter().enumerate().take(27) {
            assert_eq!(b, (i + 1) as u8, "G5 pri_A[{i}]");
        }
    }

    #[test]
    fn g5_pri_a_max_level_at_run_zero_is_27() {
        // Per audit/01 §4.2 LMAX(0) = 27 for intra. The G5 pri_A's
        // overall max should also be 27.
        assert_eq!(*G5_PRI_A.iter().max().unwrap(), 27);
    }

    #[test]
    fn g4_total_subclass_count_matches_audit() {
        // audit/01 §2.2: sub-A has 58 entries (idx 0..57), sub-B has 44
        // entries (idx 58..101). Total = 102.
        let sub_a = G4_COUNT_B + 1;
        let sub_b = G4_COUNT_A - sub_a;
        assert_eq!(sub_a, 58);
        assert_eq!(sub_b, 44);
    }

    #[test]
    fn g5_total_subclass_count_matches_audit() {
        // audit/01 §4.1: sub-A 67 entries, sub-B 35 entries.
        let sub_a = G5_COUNT_B + 1;
        let sub_b = G5_COUNT_A - sub_a;
        assert_eq!(sub_a, 67);
        assert_eq!(sub_b, 35);
    }

    // ---- G5 pri_B (round 19) ----

    #[test]
    fn g5_pri_b_run_zero_prefix() {
        // run=0 entries occupy idx 0..26 (LMAX(0)=27 for intra).
        for (i, &v) in G5_PRI_B.iter().enumerate().take(27) {
            assert_eq!(v, 0, "G5 pri_B[{i}]");
        }
    }

    #[test]
    fn g5_partition_matches_audit_table() {
        // audit/01 §4.1: sub-A's last entry idx 66 is (run=14, level=1);
        // sub-B's first entry idx 67 is (run=0, level=1, last=1).
        assert_eq!(G5_PRI_A[G5_COUNT_B], 1, "sub-A last level");
        assert_eq!(G5_PRI_B[G5_COUNT_B], 14, "sub-A last run");
        assert_eq!(G5_PRI_A[G5_COUNT_B + 1], 1, "sub-B first level");
        assert_eq!(G5_PRI_B[G5_COUNT_B + 1], 0, "sub-B first run");
    }

    #[test]
    fn g5_pri_b_max_run_is_20() {
        // audit/01 §4.1: sub-B last entry idx 101 has run=20.
        assert_eq!(G5_PRI_B[101], 20);
        assert_eq!(*G5_PRI_B.iter().max().unwrap(), 20);
    }

    #[test]
    fn g5_pri_b_sub_a_run_progression() {
        // audit/01 §4.1 sub-A run progression: r0×27, r1×10, r2×5, r3×4,
        // r4..7×3 each, r8..9×2 each, r10..14×1 each.
        let groups: &[(u8, usize)] = &[
            (0, 27),
            (1, 10),
            (2, 5),
            (3, 4),
            (4, 3),
            (5, 3),
            (6, 3),
            (7, 3),
            (8, 2),
            (9, 2),
            (10, 1),
            (11, 1),
            (12, 1),
            (13, 1),
            (14, 1),
        ];
        let mut idx = 0;
        for &(run, n) in groups {
            for _ in 0..n {
                assert_eq!(G5_PRI_B[idx], run, "G5 pri_B[{idx}] sub-A");
                idx += 1;
            }
        }
        assert_eq!(idx, G5_COUNT_B + 1, "sub-A coverage");
    }

    #[test]
    fn g5_pri_a_sub_b_canonical_level_prefix() {
        // audit/01 §4.1 sub-B run=0 row: levels 1..8. Cross-checked
        // against the binary's G5 pri_A bytes at idx 67..74.
        let base = G5_COUNT_B + 1;
        for i in 0..8 {
            assert_eq!(
                G5_PRI_A[base + i],
                (i + 1) as u8,
                "G5 pri_A[{}] sub-B run=0",
                base + i
            );
        }
    }

    #[test]
    fn g5_pri_b_sub_b_run_progression() {
        // audit/01 §4.1 sub-B run progression: r0×8, r1×3, r2..6×2 each,
        // r7..20×1 each.
        let mut groups: Vec<(u8, usize)> = vec![(0, 8), (1, 3)];
        for r in 2u8..=6 {
            groups.push((r, 2));
        }
        for r in 7u8..=20 {
            groups.push((r, 1));
        }
        let mut idx = G5_COUNT_B + 1;
        for &(run, n) in &groups {
            for _ in 0..n {
                assert_eq!(G5_PRI_B[idx], run, "G5 pri_B[{idx}] sub-B");
                idx += 1;
            }
        }
        assert_eq!(idx, G5_COUNT_A, "sub-B coverage");
    }

    #[test]
    fn g5_pri_b_no_sentinel() {
        // Cross-check: every pri_B byte is in [0, 20] (max run for G5).
        for &b in G5_PRI_B {
            assert!(b <= 20, "G5 pri_B byte {b:#x} out of range — wrong slice");
        }
    }

    // ---- ESC-extension cluster — region_060988 (round 33) ----

    #[test]
    fn esc_ext_cluster_size_matches_spec() {
        // region_060988.meta: length_bytes 2168, record_size 8, 271 records.
        // 24 slices, slice-array length 24.
        assert_eq!(ESC_EXT_CLUSTER_BYTES, 2168);
        assert_eq!(ESC_EXT_SLICE_COUNT, 24);
        assert_eq!(ESC_EXT_SLICES.len(), 24);
        assert_eq!(ESC_EXT_SLICE_META.len(), 24);
    }

    #[test]
    fn esc_ext_cluster_slice_lengths_sum_to_total() {
        // The 24 slice lengths must reconstruct the cluster contiguously.
        let total: usize = ESC_EXT_SLICE_META.iter().map(|m| m.2).sum();
        assert_eq!(total, ESC_EXT_CLUSTER_BYTES);
        // And each `&[u8]` len matches the meta length.
        for (i, slice) in ESC_EXT_SLICES.iter().enumerate() {
            assert_eq!(
                slice.len(),
                ESC_EXT_SLICE_META[i].2,
                "slice {i} length mismatch"
            );
        }
    }

    #[test]
    fn esc_ext_cluster_slice_starts_at_expected_vmas() {
        // Per `region_060988_index.csv`, the first slice begins at VMA
        // 0x1c261588 (= cluster start). Spot-check the first and last
        // slice VMAs.
        assert_eq!(ESC_EXT_SLICE_META[0].1, 0x1c261588);
        assert_eq!(ESC_EXT_SLICE_META[0].0, 0);
        // Slice 23 (last) per CSV: rel_off 2112, vma 0x1c261dc8, len 56.
        assert_eq!(ESC_EXT_SLICE_META[23].0, 2112);
        assert_eq!(ESC_EXT_SLICE_META[23].1, 0x1c261dc8);
        assert_eq!(ESC_EXT_SLICE_META[23].2, 56);
    }

    #[test]
    fn esc_ext_g_descriptor_attribution_per_spec_08() {
        // Per spec/08 §2.2 / spec/14 §2.1, each G-descriptor's pointer
        // block (`+0x0c, +0x10, +0x14, +0x18`) names four cluster slices
        // by VMA. These constants give the slice-array indices for each
        // descriptor's block.
        //
        // Hand-crosscheck against the table in `emit_esc_ext_cluster`:
        // G1 starts the cluster (slice 0 = +0x0c=0x1c261588), so its
        // index block is [0, 1, 2, 3].
        assert_eq!(ESC_EXT_G1_SLICE_INDICES, [0, 1, 2, 3]);
        // G0 follows: slices 4..=7.
        assert_eq!(ESC_EXT_G0_SLICE_INDICES, [4, 5, 6, 7]);
        // G3: slices 8..=11.
        assert_eq!(ESC_EXT_G3_SLICE_INDICES, [8, 9, 10, 11]);
        // G2: slices 12..=15.
        assert_eq!(ESC_EXT_G2_SLICE_INDICES, [12, 13, 14, 15]);
        // G5: slices 16..=19.
        assert_eq!(ESC_EXT_G5_SLICE_INDICES, [16, 17, 18, 19]);
        // G4: slices 20..=23.
        assert_eq!(ESC_EXT_G4_SLICE_INDICES, [20, 21, 22, 23]);
    }

    #[test]
    fn esc_ext_g_indices_pick_correct_vmas() {
        // Each G-block's four slice indices must point at slices whose
        // VMAs match spec/08 §2.2's per-G `(+0x0c, +0x10, +0x14, +0x18)`
        // tuple.
        let g_table: &[(&str, [usize; 4], [u32; 4])] = &[
            (
                "G0",
                ESC_EXT_G0_SLICE_INDICES,
                [0x1c261710, 0x1c261780, 0x1c261818, 0x1c261878],
            ),
            (
                "G1",
                ESC_EXT_G1_SLICE_INDICES,
                [0x1c261588, 0x1c261608, 0x1c2616a0, 0x1c2616f0],
            ),
            (
                "G2",
                ESC_EXT_G2_SLICE_INDICES,
                [0x1c2619c8, 0x1c261a40, 0x1c261af0, 0x1c261b30],
            ),
            (
                "G3",
                ESC_EXT_G3_SLICE_INDICES,
                [0x1c2618a0, 0x1c2618f8, 0x1c261968, 0x1c2619b0],
            ),
            (
                "G4",
                ESC_EXT_G4_SLICE_INDICES,
                [0x1c261c78, 0x1c261ce8, 0x1c261d90, 0x1c261dc8],
            ),
            (
                "G5",
                ESC_EXT_G5_SLICE_INDICES,
                [0x1c261b48, 0x1c261b88, 0x1c261be0, 0x1c261c50],
            ),
        ];
        for &(name, idxs, want_vmas) in g_table {
            for (k, &slice_idx) in idxs.iter().enumerate() {
                let got_vma = ESC_EXT_SLICE_META[slice_idx].1;
                assert_eq!(
                    got_vma, want_vmas[k],
                    "{name} slot {k}: slice idx {slice_idx} VMA 0x{got_vma:08x} != \
                     expected 0x{:08x}",
                    want_vmas[k]
                );
            }
        }
    }

    #[test]
    fn esc_ext_slice_lengths_match_index_csv() {
        // region_060988_index.csv per-slice lengths (verbatim, in
        // slice-index order). If the CSV ever drifts out from under the
        // build, this test catches it before the per-G attribution does.
        let want: [usize; 24] = [
            128, 152, 80, 32, 112, 152, 96, 40, 88, 112, 72, 24, 120, 176, 64, 24, 64, 88, 112, 40,
            112, 168, 56, 56,
        ];
        for (i, &want_len) in want.iter().enumerate() {
            assert_eq!(ESC_EXT_SLICE_META[i].2, want_len, "slice {i} length");
        }
    }

    #[test]
    fn esc_ext_slice_lengths_are_multiples_of_8() {
        // Per region_060988.meta: record_size 8, so every slice length
        // must be a multiple of the record stride. The build script
        // already enforces this; the runtime test catches future
        // regressions if the build script's check is ever relaxed.
        for (i, meta) in ESC_EXT_SLICE_META.iter().enumerate() {
            assert!(
                meta.2 % 8 == 0,
                "slice {i} length {} is not a multiple of 8",
                meta.2
            );
        }
    }

    #[test]
    fn esc_ext_slice_first_record_g1_lev_a() {
        // Spot-check: slice 0 (G1 +0x0c, sub-A level-extension) starts
        // at file 0x60988. Per region_060988.csv row 1 the first record
        // is (symbol_dec=19, bit_length=15) — encoded little-endian as
        // bytes `13 00 00 00 0f 00 00 00`.
        let s = ESC_EXT_SLICE_0;
        assert!(s.len() >= 8, "slice 0 too short");
        assert_eq!(s[0], 0x13, "slice 0 byte 0 (sym low)");
        assert_eq!(s[1], 0x00);
        assert_eq!(s[2], 0x00);
        assert_eq!(s[3], 0x00);
        assert_eq!(s[4], 0x0f, "slice 0 byte 4 (bl low)");
        assert_eq!(s[5], 0x00);
        assert_eq!(s[6], 0x00);
        assert_eq!(s[7], 0x00);
    }

    // ---- v1/v2 CBPY (round 75 — binary cross-check) ----

    #[test]
    fn cbpy_v1_v2_alphabet_is_sixteen_entries() {
        // Per H.263 §5.3.5 / MPEG-4 Part 2 Table B-6 the CBPY alphabet
        // has exactly 16 symbols (4-bit luma-CBP patterns 0..=15). The
        // build-time extractor filters out the 2 reserved-sentinel
        // symbols (0x10, 0x11) the binary places at LUT slots 0..1.
        assert_eq!(CBPY_V1_V2_RAW.len(), 16);
        let syms: Vec<u8> = CBPY_V1_V2_RAW.iter().map(|&(s, _, _)| s).collect();
        assert_eq!(
            syms,
            (0..=15u8).collect::<Vec<_>>(),
            "expected contiguous CBPY symbols 0..=15"
        );
    }

    #[test]
    fn cbpy_v1_v2_max_bit_length_is_six() {
        // Per spec/07 §1.3 the helper is invoked with max-bitlen 6.
        for &(_, bl, _) in CBPY_V1_V2_RAW {
            assert!((1..=6).contains(&bl), "CBPY bl={bl} out of [1,6]");
        }
    }

    #[test]
    fn cbpy_v1_v2_matches_hand_derived_table() {
        // The build cross-check already panics on mismatch, but pin the
        // invariant here too so a regression surfaces as a test failure
        // (not just a build failure) for downstream consumers.
        use crate::tables::CBPY_INTRA_TABLE;
        for &(sym, bl, code) in CBPY_V1_V2_RAW {
            let hand = CBPY_INTRA_TABLE
                .iter()
                .find(|e| e.value == sym)
                .unwrap_or_else(|| panic!("hand table missing sym {sym}"));
            assert_eq!(
                hand.bits, bl,
                "sym {sym}: hand-derived bl {} vs binary bl {bl}",
                hand.bits
            );
            assert_eq!(
                hand.code, code,
                "sym {sym}: hand-derived code 0b{:b} vs binary code 0b{:b}",
                hand.code, code
            );
        }
    }

    #[test]
    fn cbpy_v1_v2_kraft_sum_accounts_for_reserved_sentinels() {
        // Kraft sum over the 16 alphabet entries = 1 - 2*2^-6 = 31/32,
        // with the 2 leaves reserved for the (sym=0x10, sym=0x11)
        // reserved sentinels at bl=6. In 32-bit fixed-point arithmetic:
        // target = 2^32 - 2 * 2^(32-6).
        let kraft: u64 = CBPY_V1_V2_RAW
            .iter()
            .map(|&(_, bl, _)| 1u64 << (32 - bl as u32))
            .sum();
        let target: u64 = (1u64 << 32) - 2 * (1u64 << (32 - 6));
        assert_eq!(kraft, target);
    }

    #[test]
    fn cbpy_v1_v2_sentinels_are_two_at_bl_six() {
        // Per spec/07 §1.3 the binary fills the two unused 6-bit prefix
        // slots `000000` and `000001` with reserved-sentinel symbols
        // (0x10, 0x11). Both must be at bl=6 (otherwise they would
        // shadow real codewords).
        assert_eq!(CBPY_V1_V2_SENTINELS.len(), 2);
        for &(sym, bl, _) in CBPY_V1_V2_SENTINELS {
            assert!(sym >= 16, "sentinel sym {sym} inside CBPY alphabet");
            assert_eq!(bl, 6, "sentinel sym {sym} bl {bl} != 6");
        }
        // The two sentinels occupy code positions 0 and 1 of a 6-bit
        // window: `000000` and `000001`. Sort by code to compare.
        let mut codes: Vec<u32> = CBPY_V1_V2_SENTINELS.iter().map(|&(_, _, c)| c).collect();
        codes.sort_unstable();
        assert_eq!(codes, vec![0, 1]);
    }

    #[test]
    fn cbpy_v1_v2_is_prefix_free() {
        // Standard prefix-freedom check, mirrors mcbpc_v1_is_prefix_free.
        for (i, &(_, bla, ca)) in CBPY_V1_V2_RAW.iter().enumerate() {
            for (j, &(_, blb, cb)) in CBPY_V1_V2_RAW.iter().enumerate() {
                if i == j || bla == blb {
                    continue;
                }
                let (short_bl, short_c, long_bl, long_c) = if bla < blb {
                    (bla, ca, blb, cb)
                } else {
                    (blb, cb, bla, ca)
                };
                let shift = long_bl - short_bl;
                let long_prefix = long_c >> shift;
                assert_ne!(
                    long_prefix, short_c,
                    "CBPY: code 0x{short_c:x} (bl {short_bl}) is a prefix of 0x{long_c:x} (bl {long_bl})"
                );
            }
        }
    }

    #[test]
    fn cbpy_v1_v2_short_code_is_pattern_fifteen() {
        // Per H.263 Table 8 the 2-bit code `11` decodes to CBPY pattern
        // 15 (all four luma blocks coded) — the most frequent intra
        // pattern. Binary cross-check pins this load-bearing value.
        let (sym_15_bl, sym_15_code) = CBPY_V1_V2_RAW
            .iter()
            .find_map(|&(s, bl, c)| (s == 15).then_some((bl, c)))
            .unwrap();
        assert_eq!(sym_15_bl, 2);
        assert_eq!(sym_15_code, 0b11);
    }

    // ---- spec/15 §3 per-G (count_A, count_B) (round 81) ----

    #[test]
    fn g_counts_spec15_length_is_six() {
        // Six G-descriptors: G0..G5 inclusive (spec/15 §3).
        assert_eq!(G_COUNTS_SPEC15.len(), 6);
        assert_eq!(G_SUBCLASS_SIZES_SPEC15.len(), 6);
    }

    #[test]
    fn g_counts_spec15_match_constructor_disassembly() {
        // Per spec/15 §2.1 — the constructor literal-immediate stores
        // at VMAs `1c210653 / 1c21065d` (G0), `1c2106b1 / 1c2106bb` (G1),
        // `1c210710 / 1c21071a` (G2), `1c210778 / 1c210788` (G3),
        // `1c210810 / 1c21081a` (G4), `1c210862 / 1c21086c` (G5).
        //
        // These six pairs are the constructor's literal hex values
        // decoded — pinning them here surfaces drift between the spec
        // document, the build.rs source-of-truth table, and the runtime
        // constant in one shot.
        assert_eq!(
            G_COUNTS_SPEC15[0],
            (168, 98),
            "G0 — chroma+all-inter class 1"
        );
        assert_eq!(G_COUNTS_SPEC15[1], (185, 118), "G1 — intra-luma class 1");
        assert_eq!(
            G_COUNTS_SPEC15[2],
            (148, 80),
            "G2 — chroma+all-inter class 0"
        );
        assert_eq!(G_COUNTS_SPEC15[3], (132, 84), "G3 — intra-luma class 0");
        assert_eq!(
            G_COUNTS_SPEC15[4],
            (102, 57),
            "G4 — MPEG-4 Part 2 Inter LMAX baseline"
        );
        assert_eq!(
            G_COUNTS_SPEC15[5],
            (102, 66),
            "G5 — MPEG-4 Part 2 Intra LMAX baseline"
        );
    }

    #[test]
    fn g_subclass_sizes_match_spec_03_table() {
        // Per spec/03 §4.4 / spec/15 §5.2 the (sub_A, sub_B) partition
        // sizes are derived as `sub_A = count_B + 1`,
        // `sub_B = count_A - count_B - 1`. The spec table values:
        //
        //   G0: sub_A=99 sub_B=69    G3: sub_A=85 sub_B=47
        //   G1: sub_A=119 sub_B=66   G4: sub_A=58 sub_B=44
        //   G2: sub_A=81 sub_B=67    G5: sub_A=67 sub_B=35
        //
        // build.rs verifies this at build time too; the runtime test
        // catches downstream regressions if a future round ever ships a
        // partition-arithmetic change without re-checking this table.
        assert_eq!(G_SUBCLASS_SIZES_SPEC15[0], (99, 69));
        assert_eq!(G_SUBCLASS_SIZES_SPEC15[1], (119, 66));
        assert_eq!(G_SUBCLASS_SIZES_SPEC15[2], (81, 67));
        assert_eq!(G_SUBCLASS_SIZES_SPEC15[3], (85, 47));
        assert_eq!(G_SUBCLASS_SIZES_SPEC15[4], (58, 44));
        assert_eq!(G_SUBCLASS_SIZES_SPEC15[5], (67, 35));
    }

    #[test]
    fn g_subclass_arithmetic_matches_g_counts() {
        // Re-derive (sub_A, sub_B) at runtime and compare to the
        // build-time-emitted G_SUBCLASS_SIZES_SPEC15 table. Confirms
        // the two stay locked together (the build script's invariant is
        // upheld through serialisation + include!).
        for g in 0..6 {
            let (count_a, count_b) = G_COUNTS_SPEC15[g];
            let (sub_a, sub_b) = G_SUBCLASS_SIZES_SPEC15[g];
            assert_eq!(sub_a, count_b + 1, "G{g} sub_A");
            assert_eq!(sub_b, count_a - count_b - 1, "G{g} sub_B");
        }
    }

    #[test]
    fn g_counts_match_g4_g5_descriptor_constants() {
        // G_COUNTS_SPEC15 is the single source of truth — the legacy
        // per-G `G4_COUNT_A` / `G5_COUNT_A` / `G4_COUNT_B` / `G5_COUNT_B`
        // constants (emitted by `emit_g_descriptor_cluster`) must agree
        // with it. If a future round re-derives the G-descriptor cluster
        // independently and drops the build-time cross-check in
        // emit_g_descriptor_cluster, this runtime test still fires.
        let (g4_ca, g4_cb) = G_COUNTS_SPEC15[4];
        let (g5_ca, g5_cb) = G_COUNTS_SPEC15[5];
        assert_eq!(g4_ca as usize, G4_COUNT_A, "G4 count_A vs G_COUNTS_SPEC15");
        assert_eq!(g4_cb as usize, G4_COUNT_B, "G4 count_B vs G_COUNTS_SPEC15");
        assert_eq!(g5_ca as usize, G5_COUNT_A, "G5 count_A vs G_COUNTS_SPEC15");
        assert_eq!(g5_cb as usize, G5_COUNT_B, "G5 count_B vs G_COUNTS_SPEC15");
    }

    #[test]
    fn g_counts_match_g0_g3_enum_constants() {
        // Same cross-check for G0..G3 — the per-G enum module
        // (`g_enum.rs` re-exports `G{0,1,2,3}_COUNT_A` / `_COUNT_B`)
        // must agree with the spec/15 table. The values come from the
        // build.rs `emit_g_enum` calls and ultimately derive from
        // G_COUNTS_SPEC15 — but the re-export path runs through
        // `g_enum::GFamily::count_a` / `count_b` (which is the live
        // dispatch surface), so we pin the equivalence here too.
        use crate::g_enum::GExtended;
        let g_lookups: [(GExtended, usize); 4] = [
            (GExtended::G0, 0),
            (GExtended::G1, 1),
            (GExtended::G2, 2),
            (GExtended::G3, 3),
        ];
        for (fam, g_idx) in g_lookups {
            let (ca, cb) = G_COUNTS_SPEC15[g_idx];
            assert_eq!(fam.count_a(), ca as usize, "{fam:?} count_a");
            assert_eq!(fam.count_b(), cb as usize, "{fam:?} count_b");
        }
    }

    #[test]
    fn g_counts_partition_test_sums_to_alphabet_minus_one() {
        // Sub-A + sub-B should equal count_A (alphabet excluding ESC at
        // idx count_A). The ESC sentinel sits outside both sub-classes
        // per spec/15 §1 "(`idx == count_A` ⇒ ESC)". Cross-check:
        // sub_A + sub_B = count_A.
        for g in 0..6 {
            let (count_a, _) = G_COUNTS_SPEC15[g];
            let (sub_a, sub_b) = G_SUBCLASS_SIZES_SPEC15[g];
            assert_eq!(
                sub_a + sub_b,
                count_a,
                "G{g} sub_A + sub_B = {} should equal count_A = {count_a}",
                sub_a + sub_b
            );
        }
    }

    #[test]
    fn g_counts_g4_g5_share_alphabet_size() {
        // Per spec/15 §3 G4 and G5 share count_A = 102 (the MPEG-4
        // Part 2 LMAX baseline alphabet size for both Inter TCOEF and
        // Intra TCOEF tables; audit/01 §1.3). They differ only in
        // partition pivot (G4: 57 inter; G5: 66 intra) because intra
        // skewing puts more weight in sub-A.
        assert_eq!(G_COUNTS_SPEC15[4].0, G_COUNTS_SPEC15[5].0);
        assert_eq!(G_COUNTS_SPEC15[4].0, 102);
        assert_ne!(G_COUNTS_SPEC15[4].1, G_COUNTS_SPEC15[5].1);
    }
}
